server:
  port: 8888 # 端口: 8080
spring:
  gobrs:
    async:
      rules:
        - name: "test"
          content: "AService->BService,CService,FService; BService->FService,GService;"
        - name: "azh"
          content: "AService->BService,CService,FService; BService->FService,GService;"
        - name: "test1"
          content: "AService->BService->DService;AService->CService->DService"
      task-interrupt: false #局部异常是否打断主流程
